### ISSUE TITLE
Allow thematic areas to also have DAC sector codes mapped to them

### ISSUE THREAD

**Issue by markbrough** [BD-IATI/edi#100]
At the moment, DAC sector codes are only mapped to subsectors. We should also map them to thematic areas when data is imported. NB, please also ensure the character length issue does not exist as in #99

**Comment by tvldev02** [comment]
The term "thematic areas" is new to me. would you please help me to understand the issue?

**Comment by markbrough** [comment]
Sure -- thematic areas are basically a different sort of sector:
http://aims.erd.gov.bd/AIMS/CommonConfig/Index?name=Thematic%20Area

From discussions yesterday with Ismail, I understand they are structured very similarly to sectors. As I understand it, there are no sub-thematic areas (unlike sub-sectors), so I think projects should just be mapped to the top level thematic areas.

**Comment by tvldev02** [comment]
ok. got it. Thank you.

**Comment by tvldev02** [comment]
We have found the following sector vocabulary for this project http://datastore.iatistandard.org/api/1/access/activity.xml?iati-identifier=44000-P089382

```
<sector vocabulary="DAC" code="24030" percentage="33" xml:lang="en">Formal sector financial intermediaries</sector>
<sector vocabulary="DAC" code="25010" percentage="34" xml:lang="en">Business support services and institutions</sector>
<sector vocabulary="DAC" code="32130" percentage="33" xml:lang="en">
Small and medium-sized enterprises (SME) development
</sector>
<sector vocabulary="WBSector" code="FA" percentage="55" xml:lang="en">Banking</sector>
<sector vocabulary="WBSector" code="LT" percentage="15" xml:lang="en">Transmission and Distribution of Electricity</sector>
<sector vocabulary="WBSector" code="TI" percentage="15" xml:lang="en">Rural and Inter-Urban Roads and Highways</sector>
<sector vocabulary="WBSector" code="WZ" percentage="8" xml:lang="en">
General water, sanitation and flood protection sector
</sector>
<sector vocabulary="WBSector" code="YW" percentage="7" xml:lang="en">Other industry</sector>
<sector vocabulary="WBTheme" code="0039" percentage="33" xml:lang="en">
Infrastructure services for private sector development
</sector>
<sector vocabulary="WBTheme" code="0098" percentage="17" xml:lang="en">Other Financial Sector Development</sector>
<sector vocabulary="WBTheme" code="0040" percentage="17" xml:lang="en">Regulation and competition policy</sector>
<sector vocabulary="WBTheme" code="0082" percentage="17" xml:lang="en">Environmental policies and institutions</sector>
``` 

Is there any relation between WBTheme and thematic areas in AIMS?
Or should we only care about "DAC"?

**Comment by markbrough** [comment]
No. For "Sectors" and "Thematic areas" in AIMS, we only care about DAC sectors in IATI data. These can be identified where the `vocabulary` is:
* no vocabulary specified (i.e., if there is no vocabulary then we expect it to be `DAC`)
* IATI v1: `DAC`
* IATI v2: `1`

Actually, on step 6, we should only show the number of `DAC` sectors in IATI data (not the number of all sectors from other vocabularies)

**Comment by tvldev02** [comment]
Here http://bd-iati.github.io/development/sprint-5/#import-sectors
you mention sector vocabulary is 1 or 2.

So can we consider 2 vocabulary as well. (i.e. `no vocabulary` or `DAC` or `1` or `2`)

**Comment by markbrough** [comment]
Sorry, that is a good point. I agree with using vocabulary 1 or 2.

**Comment by tvldev01** [comment]
Thematic Markers are now allowed to map with IATI Code in AIMS
