### ISSUE TITLE
Remove SlimScroll

### ISSUE THREAD

**Issue by markbrough** [BD-IATI/edi#102]
I think the SlimScroll library is causing weird usability issues. For example:
* if you try to scroll up/down in a drop-down box, then it causes the page to scroll as well;
* if you scroll up/down or use the arrow keys, it causes the page to jump further than intended, making it difficult to see certain fields.

Please can we remove this library, assuming it doesn't case any major issues in doing so? (Please test once you've removed it!)

**Comment by tvldev02** [comment]
removed.
