### ISSUE TITLE
Data Quality

### ISSUE THREAD

**Issue by tvldev02** [BD-IATI/edi#103]
[AIMS_DB_DataQuallity_20170219.xlsx](https://github.com/BD-IATI/edi/files/785751/AIMS_DB_DataQuallity_20170219.xlsx)

**Comment by tvldev01** [comment]
Data Quality checking sql scripts are available here...
https://github.com/BD-IATI/edi/tree/master/Scripts/DataQuality

**Comment by tvldev01** [comment]
@markbrough  Have a look at planned disbursement data quality of following project world bank 
http://www.d-portal.org/ctrack.html?country=BD#view=act&aid=44000-P089382
http://aims.erd.gov.bd/AIMS/ProjectInfo/Edit/1374
the planned disbursement figure looks  strange

**Comment by markbrough** [comment]
I think we have pulled in both the original and revised budgets? We should only have pulled in the revised budget
