### ISSUE TITLE
Update EU projects in AIMS (using SQL) to match IATI Identifiers

### ISSUE THREAD

**Issue by markbrough** [BD-IATI/edi#108]
AIMS projects currently look like this in the AIMS:
`DCI-EDUC/2010/231125`
But in IATI they look like this:
`EU-1-2010/231-125`

Please can we use SQL to convert the DP project ID to the IATI Identifier like this:

STRING_SPLIT(DP_PROJECT_NO, "/")[1] <= YEAR
LEFT(STRING_SPLIT(STRING_SPLIT(DP_PROJECT_NO, "/")[2], 3)) <= PART A
RIGHT(STRING_SPLIT(STRING_SPLIT(DP_PROJECT_NO, "/")[2], 3)) <= PART B

Select from the `DP Project No`
Update the `IATI Identifier`
Only for EU projects

**Comment by tvldev01** [comment]
--Select Statement
```
SELECT DPProjectNo, IatiIdentifier,
	LEFT(RIGHT(DPProjectNo, 11),4) AS YEAR,
	LEFT(RIGHT(DPProjectNo, 6),3) AS PARTA,
	RIGHT(DPProjectNo, 3) AS PARTB,
	'EU-1-'+LEFT(RIGHT(DPProjectNo, 11),4)+'/'+LEFT(RIGHT(DPProjectNo, 6),3)+'-'+RIGHT(DPProjectNo, 3)
FROM tblProjectInfo
WHERE FundSourceId = 24
--AND IatiIdentifier IS NULL OR LEN(IatiIdentifier) < 1
AND DPProjectNo LIKE '%/%/%'
```

--Update Statement
```
UPDATE tblProjectInfo
SET IatiIdentifier = 'EU-1-'+LEFT(RIGHT(DPProjectNo, 11),4)+'/'+LEFT(RIGHT(DPProjectNo, 6),3)+'-'+RIGHT(DPProjectNo, 3)
WHERE FundSourceId = 24
AND DPProjectNo LIKE '%/%/%'
```
