### ISSUE TITLE
For USAID: "0 sectors", though there are sectors in the data

### ISSUE THREAD

**Issue by markbrough** [BD-IATI/edi#115]
In step 5, "Set import preferences", when using USAID data, it states that there are 0 sectors, though there are sectors available in the data - though they are published at transaction level rather than activity level.

See for example `US-1-AID-388-A-10-00002` Accelerating Agriculture Productivity Improvement (AAPI)

**Comment by tvldev01** [comment]
Need to pull Sectors from child activities like we did in case of "Aid Type"
