### ISSUE TITLE
For USAID: inserting commitments inserts new commitments, but does not remove old commitment

### ISSUE THREAD

**Issue by markbrough** [BD-IATI/edi#116]
When importing a new project, specifying that commitments should come from IATI, the existing commitments in the AIMS should be removed. Currently, they are retained, leading to double the amount expected in the data.

**Comment by tvldev02** [comment]
We have import that project again and it equals the commitments

**Comment by tvldev01** [comment]
It may be happened, due operation during deployment.

**Comment by markbrough** [comment]
I just tried and this also happened to me for this project:
http://aims.erd.gov.bd:82/AIMS/ProjectInfo/Details/1154
