### ISSUE TITLE
Exchange rate USD:USD should always be 1

### ISSUE THREAD

**Issue by markbrough** [BD-IATI/edi#119]
For this WB project, all the transactions are published in USD. The exchange rate USD:USD should always be 1. However, there are a couple of transactions (in 2009) where this is not the case:
`44000-P106216`  -- Higher Education Quality Enhancement

Would be great if you could fix this before 12pm on Thursday!

Example from commitments:

Original currency | Original value | Transaction date | Value date | BB USD exchange rate | BB exchange rate date | USD value
--- | --- | --- | --- | --- | --- | ---
USD | 81000000 | 2009-03-31 | 2009-03-31 | 1.66 | 2009-04-15 | 134,107,958.56

**Comment by tvldev02** [comment]
Data error in exchange rate. To be fixed manually by updating the correct exchange rate. :)

[Note: we have already updated this particular data.] 

![image](https://cloud.githubusercontent.com/assets/17059642/23244495/e68a3a68-f9af-11e6-95c4-d34b2121b9ef.png)
