### ISSUE TITLE
Multiple sectors not getting imported

### ISSUE THREAD

**Issue by markbrough** [BD-IATI/edi#124]
USAID "Justice for All" project `US-1-AID-388-A-12-00004` has the following sector codes at the transaction level (for commitments (transaction type 2) - which I think is all we look for?):
'11220', '12240', '12263', '13020', '13030', '13040', '14020', '15112', '15113', '15130', '15150', '15151', '15152', '15160', '15220', '21010', '23110', '24010', '25010', '31110', '31120', '33110', '41010', '41020', '72010', '72050', '74010', '91010'

For example, code `11220` maps to `Education and Religious Affairs - Primary Education`. However, when this project was imported, only one sector was imported:

| Sector | Sub Sector | Percentage of allocation |
| :---- | :---- | :---- |
| Public Administration | Not Applicable | 63.64 |

The other sectors are not currently being imported, and the total percentage only adds up to 63.64%.

**Comment by dfaruque** [comment]
Note: our criteria was `sector.vucabulary == "DAC" or "1" or "2"`
only `"15130"` is satisfying this condition. which maps to `Public Administration - Not Applicable`

however we fixed the percentage issue.

**Comment by markbrough** [comment]
@dfaruque Sorry you're right, I ran the wrong xpath expression and pulled out too many sectors. You're right that there is only one sector. Thanks.
