### ISSUE TITLE
Mismatched transactions alert

### ISSUE THREAD

**Issue by markbrough** [BD-IATI/edi#125]
For the following projects we want to take commitments and disbursements:
CA-3-A033504001
CA-3-A034963001

For the following projects, we want to take only commitments (NOT disbursements):
CA-3-A034149001
CA-3-A034608001

All four projects are currently showing "mismatched transactions" errors. In the pop up, when I click "resolve &raquo;", For the second two projects, it is also showing disbursements, even though these should not be taken from these projects given the import preferences under mapping.

We should show separate "mismatched transactions" alert entries for commitments and disbursements, and these should only be shown if import preferences have been set to take commitments / disbursements respectively.

**Comment by dfaruque** [comment]
7f069bcd4e5ae83f95fc537f659857fd1ef196ee
82137af96f2f6906a4626a97608315dddc48f4c6
and 6b30406f58252187ff12e07d3a23061711a6431b

**Comment by dfaruque** [comment]
Hi @markbrough 
I am unable to close the issue via github site.
This is because I am not a member of this repository.
Would you please grant me as a member of this repository.

**Comment by markbrough** [comment]
Thanks @dfaruque, I added you!
