### ISSUE TITLE
Duplicate transactions

### ISSUE THREAD

**Issue by markbrough** [BD-IATI/edi#128]
Duplicate transactions appear to be getting entered through the IATI import module for IATI data. I wonder if this is because different currency exchange rates are being used. Are the original currency values or USD values used to compare IATI with AIMS transactions?

I just used the "mismatched transactions" tool to reset this project "INTEGRATION: WASH & BRAC PROG" (`XM-DAC-7-PPR-29333`):
AIMS: http://aims.erd.gov.bd/AIMS/ProjectInfo/Details/2014
IATI: http://datastore.iatistandard.org/api/1/access/activity.xml?iati-identifier=XM-DAC-7-PPR-29333

There should be two commitments (EUR 5,889,269.00 and EUR -45,672.00) and one disbursement (EUR 500,000.00). Tomorrow, once the data is resynchronised, it would be good to see if this is still correct or if duplicate transactions have re-appeared.

You can also see a series of other activities that have duplicate transactions in the mismatched transactions tool. For example, ADOHEARTS (`XM-DAC-7-PPR-28992`),
AIMS: http://aims.erd.gov.bd/AIMS/ProjectInfo/Details/2013
IATI: http://datastore.iatistandard.org/api/1/access/activity.xml?iati-identifier=XM-DAC-7-PPR-28992

... has the following commitments:

Development Partner | Aid Category | Loan / Grant Number | Agreement Date (dd/MM/yyyy) | Amount in DP's Currency | Amount In USD
-- | -- | -- | -- | -- | --
Netherlands | Grant |   | 30/12/2016 | -82,584.00 | -89,206.03
Netherlands | Grant |   | 13/10/2016 | 4,598,866.00 | 5,077,445.72
Netherlands | Grant |   | 30/12/2016 | -82,584.00 | -89,207.47
Netherlands | Grant |   | 13/10/2016 | 4,598,866.00 | 5,077,445.72

**Comment by dfaruque** [comment]
We have fixed this and published.
Hopefully, duplicate transactions will not re-appeared again.

**Comment by markbrough** [comment]
I think this is fixed -- but there are a lot of activities that are still showing in the tool as having mismatched transactions? On inspection, the transactions look pretty much the same (though there are some small discrepancies, around $0.01, I guess because of currency conversion / rounding -- can you check these please)?

**Comment by dfaruque** [comment]
now we check duplicate transaction by DP's currency instead of USD 
3c80b41bf7fbfb88ae65596235df5c1651a67a72

**Comment by markbrough** [comment]
OK cool. And the remaining mismatched transactions that you see in the IATI import tool should not appear in future, once they have been dismissed?

**Comment by markbrough** [comment]
Just checked these projects again and confirm this issue is now resolved so I am closing this issue. Thanks!!
