### ISSUE TITLE
Netherlands project has not imported policy markers from IATI

### ISSUE THREAD

**Issue by markbrough** [BD-IATI/edi#132]
This Netherlands project has policy markers in IATI:
http://datastore.iatistandard.org/api/1/access/activity.xml?iati-identifier=NL-1-PPR-24789

However, no policy markers have been imported for this project:
http://aims.erd.gov.bd:82/AIMS/ProjectInfo/Details/1384

It has previously been imported from IATI, so this data should automatically be imported. Maybe this is the same issue as #131

**Comment by dfaruque** [comment]
It is working now. Please check.
