### ISSUE TITLE
Error 500 on live server for dashboard

### ISSUE THREAD

**Issue by markbrough** [BD-IATI/edi#133]
On the live server, there is an error 500 on `GetFundSources` while trying to load the drop-down list of Development Partners:
http://aims.erd.gov.bd/IATIImportSite/Modules/IATIImport/IATIImportIndex.html#/0Begin

Do we have some logging enabled for when these kind of errors occur? It would be good to send an email to TechnoVista so that they can be addressed quickly

**Comment by dfaruque** [comment]
Database server's IP was changed but not updated in the config. file by ERD.
