### ISSUE TITLE
USAID data import issues

### ISSUE THREAD

**Issue by markbrough** [BD-IATI/edi#134]
Importing USAID data to the system, there are a couple of issues:
1. When I click `Download data` in the data in the test AIMS, it says:
```
Download failed. http://datastore.iatistandard.org/api/1/access/activity.xml?recipient-country=BD&reporting-org=US-GOV-1&stream=True
```
However, this link works.

2. Subsequently, only 10 activities are downloaded, though the Datastore shows 504 in the data.

**Comment by dfaruque** [comment]
I have just tried to download data by clicking `Download Now` button from USAID dashboard in http://aims.erd.gov.bd:82/IATIImportSite and it has successfully downloaded all 504 activities.

Maybe some network related issue happened there.
