### ISSUE TITLE
hierarchy selection for multiple activities

### ISSUE THREAD

**Issue by tvldev01** [BD-IATI/edi#2]
In the mock screen you have shown how select unit of aid from multiple hierarchies of a single activity.
as shown in image below:
![hierarchysingleproject](https://cloud.githubusercontent.com/assets/17059580/13254049/b445445a-da69-11e5-8445-5f0212bd87a1.png)

But what about selecting unit of aid from multiple activities having multiple components/hierarchies  each of them, in case of DFID, most of the activities have components.
Will the UI for that be like this:
![hierarchymultipleproject](https://cloud.githubusercontent.com/assets/17059580/13254068/c7effa40-da69-11e5-8be0-1a5228832d12.png)

And what are the matching criteria in "% matched"?

**Comment by markbrough** [comment]
We should assume that donors use a hierarchy consistently in their data. Therefore, the answer for project#1 should be case with project#2 and all other projects.

The "% matched" can simply be mapping project IDs between IATI and the AIMS (as we do later in sprint 2). The aim is to to find which level of projects are generally used in the system.

E.g. in the example above, none of the hierarchy-2 projects will match to the AIMS project IDs, whereas many of the hierarchy-1 projects will.

**Comment by tvldev01** [comment]
In this case, should we proceed with checked Projects only for later stages (further filtering and matching between IATI and AIMS projects), leaving the unchecked projects/components.

We have seen DFID projects at hierarchy 1 have only basic information of projects and no transaction information, transaction information are stored in related activities or components at hierarchy 2. It seems like hierarchy 1 and 2 are like master-detail information of a project.

**Comment by markbrough** [comment]
In the "Filter DP activities" page we can filter out the projects we don't want to import (showing only hierarchy 1 or hierarchy 2 projects, as the user determines on this "Hierarchy" screen). For hierarchical activities, in later sprints we will also have the option of filtering out components (i.e. hierarchy 2 activities). But I would avoid allowing a mix of different levels to be selected at this stage as it will become confusing - so I think it's far preferable to make the user select one level for all projects at this stage.

In DFID's case, the hierarchy 1 activities have very little information, but they act as containers for all the sub-components and the titles and descriptions are better at hierarchy 1 level. So, mapping from hierarchy 1 (taking all the components with the project, for now) is probably the simplest route for them for now.

**Comment by markbrough** [comment]
Let's Skype if that doesn't make sense or if you disagree!
