### ISSUE TITLE
Investigate parse errors

### ISSUE THREAD

**Issue by markbrough** [BD-IATI/edi#35]
Implement workarounds / fix bugs where possible

Parse errors were noted on the following organisations:

* [ ] Australia
* [ ] Denmark
* [ ] Sweden
* [ ] Switzerland

**Comment by tvldev02** [comment]
In Sweden data we have found that the IATIIdentifier length is more than 50; but in aims database it should be 50 character maximum.

<iati-identifier>SE-0-SE-24-Swedish-Institute-Scholarship-Programmes-5-666-11420</iati-identifier>

What should we do for that case?

**Comment by tvldev02** [comment]
We have ignore those activities for now...

**Comment by matmaxgeds** [comment]
Hi, rather than ignoring these activities, can the IATIIdentifier be truncated at 40 characters and then concatenated with '*truncated'?

**Comment by tvldev02** [comment]
Ok. Great idea. 
We will implement this.
Thanks

**Comment by matmaxgeds** [comment]
Great.
