### ISSUE TITLE
Import sectors

### ISSUE THREAD

**Issue by markbrough** [BD-IATI/edi#37]
@markbrough to provide mapping between CRS Sector codes and BD govt sector codes

**Comment by aidreview** [comment]
Presumably this should hook into the existing mapping built into the AIMS?

And what do we do about non CRS Sector codes in IATI, drop them and request a BD Sector?

**Comment by aidreview** [comment]
Apologies for posting as another user (this is Matt!)

**Comment by markbrough** [comment]
Yes -- we should use the existing mapping functionality in the AIMS, and the codes to the extent they have already been filled out.

Re non-CRS sector codes, unless we find any other reasonably standard vocabularies -- shared by several organisations (I think unlikely) -- then I think we should drop them and flag that as something that needs to be added in the AIMS in the course of normal data quality improvement processes.
