### ISSUE TITLE
EU data shows as BD percentage 0%

### ISSUE THREAD

**Issue by markbrough** [BD-IATI/edi#4]
However, in the hierarchy=1 activities, Bangladesh is correctly specified as the country, though there is no `percentage` attribute on the `recipient-country` tag. NB that [the percentage attribute is optional](http://iatistandard.org/104/activity-standard/iati-activities/iati-activity/recipient-country/) if only one recipient-country is declared

http://datastore.iatistandard.org/api/1/access/activity.xml?iati-identifier=EU-1-2010/21533/1

```xml
<recipient-country code="BD">Bangladesh</recipient-country>
```

I think we should handle multiple countries this way for now:

* if multiple countries are listed, take the percentage attribute for each country
* **if there is only one country listed, assume the percentage is 100%**

In the future we may want to add in a couple of other checks:

* if multiple countries are listed and the percentage attribute is not provided... I guess this should raise an exception for now. Ideally in future we would have some way of logging when exceptions are raised and why, and presenting that information back to the user
* if the countries do not add to 100%, we may also want to raise an exception.

This issue will also be the same for `<sector>` and possibly a few other elements.

**Comment by tvldev02** [comment]
Fixed
