### ISSUE TITLE
Matching IATIIdentifier for ADB 

### ISSUE THREAD

**Issue by tvldev02** [BD-IATI/edi#47]
e.g
Project title: MFF-BAN RAILWAY SECTOR INVESTMENT PROGRAM
In IATI data the identifier looks like
46004-32234-023-LN2316
where in AIMS it has DP Project No: 32234-023

Should we match them by using contains operation?

**Comment by tvldev01** [comment]
I think we can use "contain" check instead of current EndWith check...

**Comment by tvldev02** [comment]
Thanks
