### ISSUE TITLE
3.2 Newly created executing organisations don't appear

### ISSUE THREAD

**Issue by markbrough** [BD-IATI/edi#69]
In the "Implementing organisation" column, I should see the implementing (executing) organisation I created in step 3.1 (e.g. for Netherlands - created Anne Frank Stichting -- I should see that listed in the third column)

**Comment by tvldev02** [comment]
Now I have added new organization to AIMS database for NGO type only. 
Should we add DP and Govt. as well?
If yes then what about MinistryId for Govt./MinistryAgency which is a required filed in AIMS DB
And FundSourceCategoryId and CurrencyId  for DP/FundSource?

**Comment by markbrough** [comment]
Yes, we should implement for both DP and Govt. Is it possible to add an alert to the system administrator (I guess Sabbir?) to alert him that a new DP or Govt ministry/agency has been created so that he can take a look at it?
For Govt:
* MinistryID we could map to "Ministry: Not Available" (and this could then be corrected later)

For DP:
* FundSourceCategoryID we could map to "Others" (and then this can be corrected later)
* CurrencyID let's use USD (I guess we are converting all the amounts to USD anyway so it doesn't really matter?)

**Comment by markbrough** [comment]
@tvldev02 would be great if this could be redeployed to the server when you have a moment!

**Comment by tvldev02** [comment]
redeployed.

**Comment by markbrough** [comment]
Looks great 👍
