### ISSUE TITLE
Serve IATI import module from same port as main AIMS

### ISSUE THREAD

**Issue by markbrough** [BD-IATI/edi#80]
At the moment, the IATI import module is served from port 82 and the test AIMS from 83. This was due to conflicts in routes between the two applications. We need to serve from the same port.

**Comment by mijaved** [comment]
done!
AIMS Demo: http://aims.erd.gov.bd:82/
AIMS BD IATI Module: http://aims.erd.gov.bd:82/IATIImportSite/#/Home

**Comment by markbrough** [comment]
👍
