### ISSUE TITLE
On Firefox, step 3.2, "Next" button doesn't work

### ISSUE THREAD

**Issue by markbrough** [BD-IATI/edi#86]
On Step 3.2, there is a bug in Firefox (works OK in Chrome) where the "Next..." button does not work. Perhaps an issue with the Angular-UI pop-up function?

**Comment by tvldev02** [comment]
can't reproduce.

**Comment by markbrough** [comment]
This is an issue with Bootstrap: https://github.com/angular-ui/bootstrap/issues/3687#issuecomment-141480009

It appears on Firefox and Safari on OSX: https://gist.github.com/cvrebert/68659d0333a578d75372
