### ISSUE TITLE
In AIMS, IATI codes for subsectors have a low character limit

### ISSUE THREAD

**Issue by markbrough** [BD-IATI/edi#99]
The "IATI code" field alongside a subsector in AIMS has a low character limit. We need this to be at least 350 characters or so, so that we can fit all the codes in separated with the `|` symbol. Can we increase the character limit to something like 10000 so that there is effectively no limit?

**Comment by tvldev01** [comment]
Sectors and Subsectors are now allowed to map with IATI Code in AIMS upto 1000 chars
